name: Terraform Validation

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.hcl"
      - ".github/workflows/terraform-validation.yml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        directory:
          - bootstrap
          - modules/networking
          - modules/security/flow-logs
          - modules/security/security-groups
          - stacks/networking/dev
          - stacks/security/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"

      - name: Terraform Init
        working-directory: ${{ matrix.directory }}
        run: terraform init -backend=false

      - name: Terraform Format Check
        working-directory: ${{ matrix.directory }}
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ${{ matrix.directory }}
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: TFLint
        working-directory: ${{ matrix.directory }}
        run: |
          tflint --init
          tflint

    checkov:
      name: Checkov Security Scan
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Checkov Security Scan
          uses: bridgecrewio/checkov-action@v12
          with:
            directory: .
            framework: terraform
